---
- hosts: localhost
  connection: local
  gather_facts: false
  roles:
    - { role: cfn }

- hosts: server
  remote_user: ec2-user
  become: yes
  roles:
    - role: server

- hosts: agents
  remote_user: ubuntu
  become: yes
  roles:
    - role: agent